name: Run the script

on:
    workflow_dispatch:
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: pull own repo
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v1
              with:
                python-version: 3.11
            - name: list current files
              working-directory: ./standalone
              run: |
                ls
            - name: run the script
              working-directory: ./standalone
              run: |
                python test.py

