name: Run the script

on:
    workflow_dispatch:
jobs:
    run:
        runs-on: self-hosted
        steps:
            - name: pull own repo
              uses: actions/checkout@v4
            - name: list current files
              run: |
                ls
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: run the script
              run: |
                python test.py

