name: Run the script

on:
    workflow_dispatch:
jobs:
    run:
        runs-on: self-hosted
        steps:
            - name: pull own repo
              uses: actions/checkout@v4
            - name: test
              run: |
                ls
