name: Run the script

on:
    workflow_dispatch:
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: pull own repo
              uses: actions/checkout@v4
            - name: list current files
              run: |
                ls
            - name: install dependencies
              run: |
                pip install pipenv
                pipenv install
            - name: run the script
              run: |
                python test.py

